### ISSUE TITLE
Tutorial system todo

### ISSUE THREAD

**Issue by jeffreykog** [nailed/nailed#21]
- [x] Allow for stages to be added in the mappack configuration
- [x] Teleporting between stages
- [x] Give players an item to easily switch to the next stage instead of typing a command
- [x] Give the item on map switch
- [x] Give the item on world join
